Okay! Let's try the gym business. Cliff walking environment is perfect.

In [1]:
import gym
import numpy as np
import ToyEnv
import psrl
import PosteriorSamplerGMM

In [ ]:
env = gym.make('CliffWalking-v0')

In [ ]:
observation, info = env.reset()
print(observation)
print(info)
np.unravel_index(observation, env.shape)

In [ ]:
action = env.action_space.sample()
print(action)
observation, reward, terminated, truncated, info = env.step(3)
print(observation)
print(env.action_space.n)
print(reward)
print(env.P[observation][2])

# Testing ToyEnv

In [2]:
new_env = ToyEnv.ToyEnv()
init_state = new_env.reset()
print(init_state)

1


In [3]:
next_state, reward = new_env.step(1)
print(reward)
print(next_state)

3.360012099714048
2


# Testing Gibbs sampler

In [4]:
# Generate some data for state-action pair (0, 2)
means = new_env._compute_means(0, 2)
sigma = new_env.true_Sigma
pis = new_env.true_pi
data = np.zeros((100,))
for i in range(100):
    k = np.random.choice(len(pis), p=pis)
    data[i] = np.random.normal(loc=means[k], scale=sigma[k])

In [5]:
print(means)
print(sigma)
print(pis)

[2 5 8]
[0.1 0.1 0.1]
[0.16666667 0.16666667 0.66666667]


In [15]:
gibbs = PosteriorSamplerGMM.GibbsSamplerGMM(2000, 3)

In [16]:
samples = gibbs.fit(data)

In [17]:
print(samples[-1])

(array([8.00110863, 1.99071345, 4.83173804]), array([0.05335856, 0.14612603, 0.19519818]), array([0.66291525, 0.16964809, 0.16743666]))
